#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT( \
    KC_Q, KC_C, KC_H, KC_M, KC_G, KC_Y, KC_K, KC_O, KC_J, KC_QUOT, \
        LCTL_T(KC_R), LALT_T(KC_S), LGUI_T(KC_N), LSFT_T(KC_T), KC_P, KC_W, RSFT_T(KC_U), RGUI_T(KC_E), RALT_T(KC_I), RCTL_T(KC_A), \
        KC_X, KC_B, KC_L, KC_D, KC_Z, KC_V, KC_F, KC_DOT, KC_COMM, KC_SLSH, \
        LCTL(KC_C), LCTL(KC_V), KC_VOLD, KC_VOLU, \
        LT(1,KC_ENT), LT(2,KC_SPC), LT(2,KC_SPC), LT(1,KC_PENT), \
        KC_BSPC, TG(4), KC_CAPS, KC_DEL, \
        LT(3,KC_ESC), DEBUG, RESET, LT(3,KC_TAB)),
	[1] = LAYOUT( \
    KC_TILD, KC_GRV, KC_PERC, KC_NO, KC_NO, KC_CIRC, KC_DLR, KC_BSLS, KC_EXLM, KC_DQUO, \
        LCTL_T(KC_LCBR), LALT_T(KC_LPRN), LGUI_T(KC_RPRN), LSFT_T(KC_RCBR), KC_NO, KC_AMPR, RSFT_T(KC_EQL), RGUI_T(KC_UNDS), RALT_T(KC_HASH), RCTL_T(KC_COLN), \
        KC_LT, KC_LBRC, KC_RBRC, KC_GT, KC_NO, KC_AT, KC_ASTR, KC_PLUS, KC_MINS, KC_SCLN, \
        LCTL(KC_Z), LCTL(KC_X), KC_NO, KC_NO, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT( \
    KC_NO, KC_BTN2, KC_MS_U, KC_BTN1, KC_NO, KC_NO, KC_PGUP, KC_UP, KC_HOME, KC_NO, \
        KC_WH_D, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_U, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, \
        KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO, KC_NO, KC_PGDN, KC_NO, KC_END, KC_NO, \
        KC_VOLD, KC_VOLU, KC_NO, KC_NO, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT( \
    KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, \
        KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, \
        KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_F11, KC_F12, \
        KC_F11, KC_F12, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT( \
    KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, \
        KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, \
        KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_P, KC_NO, \
        KC_F17, KC_F18, KC_COMM, KC_DOT, \
        MO(5), KC_SPC, KC_NO, KC_NO, \
        KC_F13, KC_TRNS, TG(4), TG(4), \
        KC_F15, LSFT(KC_TAB), TG(4), TG(4)),
	[5] = LAYOUT( \
    KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, \
        KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, \
        KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
        KC_VOLD, KC_VOLU, KC_NO, KC_NO, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

